### ISSUE TITLE
Dúvida sobre JSONSerialization.

### ISSUE THREAD

**Issue by reserved1** [otavioalbucosta/FolderOrganizer#1]
https://github.com/otavioalbucosta/FolderOrganizer/blob/488a18fbf89b832508ea221a14c7e3fd29dfce8e/Sources/FolderOrganizerLib/organize.swift#L34

Minha dúvida é sobre o [.mutableLeaves, .mutableContainers].

O que eles são no código? são valores armazenados em 'data' ou é algo mais interno como a forma como eles vão organizar os arquivos?

**Comment by otavioalbucosta** [comment]
Boa tarde reserved1.

.mutableLeaves e .mutableContainers são opções que mudam a forma que o seu JSON é carregado para a variável `JSONdata`
.mutableLeaves serve para avisar que as strings "folhas" dentro do objeto JSON serão mutáveis.
.mutableContainers serve para avisar que os arrays e dicionários armazenados dentro do objeto JSON também serão mutáveis.

Fontes: https://developer.apple.com/documentation/foundation/jsonserialization/readingoptions
