### ISSUE TITLE
Nome das variáveis

### ISSUE THREAD

**Issue by laisbastosbg** [otavioalbucosta/FolderOrganizer#2]
Para melhorar a legibilidade do código sugiro renomear a seguinte variável para fileManager:

https://github.com/otavioalbucosta/FolderOrganizer/blob/488a18fbf89b832508ea221a14c7e3fd29dfce8e/Sources/FolderOrganizerLib/organize.swift#L41

assim:

```swift
let fileMananger = FileManager.default
```

É importante facilitar a leitura do código, mesmo que o significado de fmanager seja óbvio nesse contexto. Imagina que uma pessoa já ta com o cérebro derretido de passar o dia lendo o código, é muito mais fácil ler e compreender fileManager do que é fmanager

Também há várias variáveis de nome composto em lowercase, o que também dificulta a leitura. Exemplo:

https://github.com/otavioalbucosta/FolderOrganizer/blob/488a18fbf89b832508ea221a14c7e3fd29dfce8e/Sources/FolderOrganizerLib/organize.swift#L42

https://github.com/otavioalbucosta/FolderOrganizer/blob/488a18fbf89b832508ea221a14c7e3fd29dfce8e/Sources/FolderOrganizerLib/organize.swift#L44

https://github.com/otavioalbucosta/FolderOrganizer/blob/488a18fbf89b832508ea221a14c7e3fd29dfce8e/Sources/FolderOrganizerLib/organize.swift#L47

**Comment by otavioalbucosta** [comment]
Resolvido no commit de mensagem "Better variable names"
Obrigado 👍
